name = "IndexFunArrays"
uuid = "613c443e-d742-454e-bfc6-1d7f8dd76566"
authors = ["Rainer Heintzmann <heintzmann@gmail.com>", "Felix Wechsler (roflmaostc) <fxw+git@mailbox.org>"]
version = "0.1.5"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
julia = "1.6"

[extras]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Random", "BenchmarkTools"]
